name: stacko_tower
description: "StackoTower - pave one continuous road across every plot!"
publish_to: 'none'
version: 1.1.0+14

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.11.1
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/stacko_icon.webp
    - assets/stacko_name.webp
    - assets/gameplay/
    - assets/splash/
    - assets/additional_assets/notifications/
    - assets/additional_assets/no_wifi/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/stacko_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#1A1A2E"
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "assets/stacko_icon.png"
