/// A "Site Paver" route puzzle: pave one continuous road that visits every
/// open plot exactly once, starting at [startIndex] and finishing at
/// [exitIndex]. Some lots contain obstacle blocks ([walls]) you must route
/// around.
///
/// Two ways to build a level:
///  * [RouteLevel.open] — a plain open rectangle (solved by the snake path).
///  * [RouteLevel.grid] — an authored lot with obstacle blocks; the solvability
///    of every built-in lot is proven by the Hamiltonian solver in
///    `test/route_level_test.dart`.
class RouteLevel {
  RouteLevel._({
    required this.levelNumber,
    required this.name,
    required this.rows,
    required this.cols,
    required this.coinReward,
    required this.walls,
    required this.startIndex,
    required this.exitIndex,
  });

  factory RouteLevel.open({
    required int levelNumber,
    required String name,
    required int rows,
    required int cols,
    required int coinReward,
  }) {
    // Snake from (0,0) ends at the right corner when rows is odd, else left.
    final exitC = rows.isOdd ? cols - 1 : 0;
    return RouteLevel._(
      levelNumber: levelNumber,
      name: name,
      rows: rows,
      cols: cols,
      coinReward: coinReward,
      walls: const <int>{},
      startIndex: 0,
      exitIndex: (rows - 1) * cols + exitC,
    );
  }

  /// Raw constructor for procedurally forged lots (see `LevelForge`).
  factory RouteLevel.raw({
    required int levelNumber,
    required String name,
    required int rows,
    required int cols,
    required int coinReward,
    required Set<int> walls,
    required int startIndex,
    required int exitIndex,
  }) =>
      RouteLevel._(
        levelNumber: levelNumber,
        name: name,
        rows: rows,
        cols: cols,
        coinReward: coinReward,
        walls: walls,
        startIndex: startIndex,
        exitIndex: exitIndex,
      );

  /// Authored lot. [art] rows use `#` for an obstacle block and any other
  /// character for open floor. [start]/[exit] are (row, col) coordinates.
  factory RouteLevel.grid({
    required int levelNumber,
    required String name,
    required int coinReward,
    required List<String> art,
    required (int, int) start,
    required (int, int) exit,
  }) {
    final rows = art.length;
    final cols = art.first.length;
    assert(art.every((r) => r.length == cols),
        'Lot $levelNumber "$name": ragged rows');
    final walls = <int>{};
    for (var r = 0; r < rows; r++) {
      for (var c = 0; c < cols; c++) {
        if (art[r][c] == '#') walls.add(r * cols + c);
      }
    }
    final si = start.$1 * cols + start.$2;
    final ei = exit.$1 * cols + exit.$2;
    assert(!walls.contains(si), 'Lot $levelNumber: start on a wall');
    assert(!walls.contains(ei), 'Lot $levelNumber: exit on a wall');
    return RouteLevel._(
      levelNumber: levelNumber,
      name: name,
      rows: rows,
      cols: cols,
      coinReward: coinReward,
      walls: walls,
      startIndex: si,
      exitIndex: ei,
    );
  }

  final int levelNumber;
  final String name;
  final int rows;
  final int cols;
  final int coinReward;
  final Set<int> walls;
  final int startIndex;
  final int exitIndex;

  int get startR => startIndex ~/ cols;
  int get startC => startIndex % cols;
  int get exitR => exitIndex ~/ cols;
  int get exitC => exitIndex % cols;

  int index(int r, int c) => r * cols + c;
  bool isWall(int r, int c) => walls.contains(index(r, c));
  bool isWallIndex(int i) => walls.contains(i);

  /// Open plots that must be paved.
  int get plotCount => rows * cols - walls.length;
}

/// A themed group of campaign lots.
class District {
  const District({
    required this.name,
    required this.tagline,
    required this.firstLevel,
    required this.lastLevel,
  });

  final String name;
  final String tagline;
  final int firstLevel;
  final int lastLevel;

  bool contains(int levelNumber) =>
      levelNumber >= firstLevel && levelNumber <= lastLevel;
  int get levelCount => lastLevel - firstLevel + 1;
}

const List<District> districts = [
  District(
      name: 'Foundation Yard',
      tagline: 'Where every road begins',
      firstLevel: 1,
      lastLevel: 15),
  District(
      name: 'Neon Harbor',
      tagline: 'Pave the glowing docks',
      firstLevel: 16,
      lastLevel: 30),
  District(
      name: 'Skyline Heights',
      tagline: 'Roads above the clouds',
      firstLevel: 31,
      lastLevel: 45),
  District(
      name: 'Crystal Megapolis',
      tagline: 'The final frontier of paving',
      firstLevel: 46,
      lastLevel: 60),
];

District districtOf(int levelNumber) => districts.firstWhere(
      (d) => d.contains(levelNumber),
      orElse: () => districts.last,
    );

/// All Site Paver lots, ordered by difficulty. Early lots are open; later lots
/// add obstacle blocks. Every lot is proven solvable by the test suite.
final List<RouteLevel> routeLevels = <RouteLevel>[
  RouteLevel.open(levelNumber: 1, name: 'Foundation Lot', rows: 3, cols: 3, coinReward: 50),
  RouteLevel.open(levelNumber: 2, name: 'Corner Plot', rows: 4, cols: 4, coinReward: 70),
  RouteLevel.open(levelNumber: 3, name: 'Service Road', rows: 4, cols: 5, coinReward: 90),
  RouteLevel.grid(
    levelNumber: 4,
    name: 'First Pillar',
    coinReward: 110,
    start: (0, 0),
    exit: (4, 4),
    art: const [
      '.....',
      '..#..',
      '..#..',
      '.....',
      '.....',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 5,
    name: 'Twin Posts',
    coinReward: 130,
    start: (0, 0),
    exit: (4, 5),
    art: const [
      '......',
      '......',
      '..##..',
      '......',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 6,
    name: 'Gate Posts',
    coinReward: 150,
    start: (0, 0),
    exit: (2, 5),
    art: const [
      '......',
      '......',
      '.##...',
      '...##.',
      '......',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 7,
    name: 'Loading Bay',
    coinReward: 180,
    start: (0, 0),
    exit: (5, 6),
    art: const [
      '.......',
      '.......',
      '.##....',
      '....##.',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 8,
    name: 'Central Mast',
    coinReward: 210,
    start: (0, 0),
    exit: (6, 6),
    art: const [
      '.......',
      '...#...',
      '...#...',
      '.......',
      '...#...',
      '...#...',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 9,
    name: 'Depot Blocks',
    coinReward: 240,
    start: (0, 0),
    exit: (2, 7),
    art: const [
      '........',
      '........',
      '..##.##.',
      '........',
      '........',
      '........',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 10,
    name: 'Wide Terminal',
    coinReward: 280,
    start: (0, 0),
    exit: (6, 8),
    art: const [
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '....##...',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 11,
    name: 'Four Corners',
    coinReward: 320,
    start: (0, 0),
    exit: (2, 7),
    art: const [
      '........',
      '........',
      '..##.##.',
      '........',
      '........',
      '..##.##.',
      '........',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 12,
    name: 'Harbor Works',
    coinReward: 360,
    start: (0, 0),
    exit: (7, 8),
    art: const [
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 13,
    name: 'Grand Avenue',
    coinReward: 420,
    start: (0, 0),
    exit: (7, 8),
    art: const [
      '..........',
      '..##..##..',
      '..........',
      '..........',
      '....##....',
      '..........',
      '..........',
      '..##..##..',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 14,
    name: 'Tower District',
    coinReward: 460,
    start: (0, 0),
    exit: (8, 8),
    art: const [
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 15,
    name: 'Megastructure',
    coinReward: 520,
    start: (0, 8),
    exit: (8, 0),
    art: const [
      '.........',
      '.........',
      '..##.##..',
      '.........',
      '....##...',
      '.........',
      '..##.##..',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 16,
    name: 'Dockside Twins',
    coinReward: 542,
    start: (0, 0),
    exit: (5, 4),
    art: const [
      '......',
      '......',
      '......',
      '....#.',
      '....#.',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 17,
    name: 'Crane Alley',
    coinReward: 564,
    start: (5, 6),
    exit: (0, 0),
    art: const [
      '.......',
      '.......',
      '..##...',
      '.......',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 18,
    name: 'Pier Gates',
    coinReward: 586,
    start: (0, 5),
    exit: (4, 0),
    art: const [
      '......',
      '.#....',
      '.#....',
      '......',
      '......',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 19,
    name: 'Cargo Rows',
    coinReward: 608,
    start: (0, 0),
    exit: (5, 6),
    art: const [
      '.......',
      '.......',
      '.......',
      '....##.',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 20,
    name: 'Harbor Cross',
    coinReward: 630,
    start: (5, 0),
    exit: (1, 5),
    art: const [
      '......',
      '...##.',
      '......',
      '......',
      '..##..',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 21,
    name: 'Tide Lock',
    coinReward: 652,
    start: (0, 0),
    exit: (5, 6),
    art: const [
      '.......',
      '.......',
      '.##....',
      '....#..',
      '....#..',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 22,
    name: 'Ferry Yard',
    coinReward: 674,
    start: (5, 0),
    exit: (0, 4),
    art: const [
      '......',
      '....#.',
      '.#..#.',
      '.#....',
      '......',
      '......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 23,
    name: 'Buoy Field',
    coinReward: 696,
    start: (0, 0),
    exit: (6, 7),
    art: const [
      '........',
      '........',
      '........',
      '..#.##..',
      '..#.....',
      '........',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 24,
    name: 'Anchor Point',
    coinReward: 718,
    start: (0, 0),
    exit: (2, 6),
    art: const [
      '.......',
      '.......',
      '.#.#...',
      '.#.#...',
      '.......',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 25,
    name: 'Salt Wharf',
    coinReward: 740,
    start: (6, 7),
    exit: (0, 0),
    art: const [
      '........',
      '...#....',
      '...#....',
      '........',
      '...#....',
      '...#....',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 26,
    name: 'Container Maze',
    coinReward: 762,
    start: (6, 0),
    exit: (0, 4),
    art: const [
      '.......',
      '....##.',
      '.......',
      '.......',
      '....##.',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 27,
    name: 'Night Pier',
    coinReward: 784,
    start: (6, 0),
    exit: (0, 7),
    art: const [
      '........',
      '........',
      '.##.....',
      '....##..',
      '..#.....',
      '..#.....',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 28,
    name: 'Beacon Walk',
    coinReward: 806,
    start: (6, 6),
    exit: (0, 2),
    art: const [
      '.......',
      '..#.##.',
      '..#....',
      '.......',
      '...#...',
      '...#...',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 29,
    name: 'Dry Dock',
    coinReward: 828,
    start: (0, 0),
    exit: (6, 7),
    art: const [
      '........',
      '.....#..',
      '...#.#..',
      '...#....',
      '.....#..',
      '.....#..',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 30,
    name: 'Harbor Master',
    coinReward: 850,
    start: (6, 0),
    exit: (0, 2),
    art: const [
      '.......',
      '..##...',
      '.......',
      '.#.....',
      '.#.##..',
      '.......',
      '.......',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 31,
    name: 'Mezzanine',
    coinReward: 872,
    start: (7, 0),
    exit: (0, 6),
    art: const [
      '.........',
      '...##.#..',
      '......#..',
      '.........',
      '..#......',
      '..#......',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 32,
    name: 'Steel Spine',
    coinReward: 894,
    start: (0, 0),
    exit: (7, 4),
    art: const [
      '........',
      '........',
      '........',
      '......#.',
      '.#....#.',
      '.#......',
      '....##..',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 33,
    name: 'Glass Court',
    coinReward: 916,
    start: (7, 0),
    exit: (0, 8),
    art: const [
      '.........',
      '.....#...',
      '.....#...',
      '.........',
      '.#.......',
      '.#.#.....',
      '...#.....',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 34,
    name: 'Vent Shafts',
    coinReward: 938,
    start: (0, 0),
    exit: (4, 7),
    art: const [
      '........',
      '........',
      '....##..',
      '........',
      '...##...',
      '........',
      '.....##.',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 35,
    name: 'Sky Lobby',
    coinReward: 960,
    start: (7, 8),
    exit: (0, 2),
    art: const [
      '.........',
      '.##......',
      '.........',
      '...#...#.',
      '...#...#.',
      '.........',
      '...##....',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 36,
    name: 'Twin Elevators',
    coinReward: 982,
    start: (0, 7),
    exit: (6, 0),
    art: const [
      '........',
      '..##....',
      '........',
      '.....##.',
      '..##....',
      '........',
      '.##.....',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 37,
    name: 'Girder Forest',
    coinReward: 1004,
    start: (7, 0),
    exit: (0, 8),
    art: const [
      '.........',
      '.##......',
      '.........',
      '.........',
      '...##....',
      '......#..',
      '..##..#..',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 38,
    name: 'Helipad Run',
    coinReward: 1026,
    start: (7, 7),
    exit: (0, 1),
    art: const [
      '........',
      '.#.##...',
      '.#......',
      '.....##.',
      '........',
      '.#......',
      '.#......',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 39,
    name: 'Cloud Deck',
    coinReward: 1048,
    start: (0, 8),
    exit: (8, 0),
    art: const [
      '.........',
      '....#....',
      '....#....',
      '.#.......',
      '.#.....#.',
      '.......#.',
      '....#....',
      '....#....',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 40,
    name: 'Antenna Row',
    coinReward: 1070,
    start: (8, 7),
    exit: (0, 0),
    art: const [
      '........',
      '......#.',
      '...##.#.',
      '........',
      '........',
      '.##.#...',
      '....#...',
      '........',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 41,
    name: 'Penthouse Loop',
    coinReward: 1092,
    start: (8, 8),
    exit: (0, 0),
    art: const [
      '.........',
      '.....#...',
      '.....#...',
      '.........',
      '.........',
      '....##...',
      '.##......',
      '.....##..',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 42,
    name: 'Wind Brace',
    coinReward: 1114,
    start: (0, 7),
    exit: (4, 0),
    art: const [
      '........',
      '..#..#..',
      '..#..#..',
      '........',
      '.##.....',
      '........',
      '....#...',
      '....#...',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 43,
    name: 'Observation Ring',
    coinReward: 1136,
    start: (0, 8),
    exit: (8, 2),
    art: const [
      '.........',
      '.##......',
      '......#..',
      '......#..',
      '.........',
      '......##.',
      '..#......',
      '..#.##...',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 44,
    name: 'Spire Base',
    coinReward: 1158,
    start: (0, 0),
    exit: (4, 7),
    art: const [
      '........',
      '....##..',
      '........',
      '..##....',
      '.....##.',
      '........',
      '.##.##..',
      '........',
      '........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 45,
    name: 'Skyline Crown',
    coinReward: 1180,
    start: (0, 8),
    exit: (8, 0),
    art: const [
      '.........',
      '.#.......',
      '.#.#.....',
      '...#.##..',
      '.........',
      '.........',
      '...#..##.',
      '...#.....',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 46,
    name: 'Neon Plaza',
    coinReward: 1202,
    start: (0, 8),
    exit: (8, 0),
    art: const [
      '.........',
      '.#.......',
      '.#...#...',
      '.....#.#.',
      '.......#.',
      '..##.....',
      '.........',
      '......##.',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 47,
    name: 'Circuit Block',
    coinReward: 1224,
    start: (8, 9),
    exit: (2, 0),
    art: const [
      '..........',
      '.##.......',
      '..........',
      '........#.',
      '...#....#.',
      '...#.#....',
      '.....#.#..',
      '.......#..',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 48,
    name: 'Hologram Square',
    coinReward: 1246,
    start: (0, 8),
    exit: (8, 0),
    art: const [
      '.........',
      '.........',
      '..##.....',
      '.........',
      '....##.#.',
      '.#.....#.',
      '.#.##....',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 49,
    name: 'Data Spine',
    coinReward: 1268,
    start: (0, 0),
    exit: (4, 9),
    art: const [
      '..........',
      '....#.....',
      '....#.....',
      '..........',
      '.....#....',
      '..##.#....',
      '..........',
      '.##....##.',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 50,
    name: 'Chrome Garden',
    coinReward: 1290,
    start: (0, 0),
    exit: (8, 6),
    art: const [
      '.........',
      '......#..',
      '.##...#..',
      '....#....',
      '..#.#....',
      '..#......',
      '......#..',
      '...##.#..',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 51,
    name: 'Prism Court',
    coinReward: 1312,
    start: (0, 0),
    exit: (8, 9),
    art: const [
      '..........',
      '.....##...',
      '.#........',
      '.#....##..',
      '....#.....',
      '....#.#...',
      '.#....#...',
      '.#........',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 52,
    name: 'Quantum Yard',
    coinReward: 1334,
    start: (0, 0),
    exit: (4, 8),
    art: const [
      '.........',
      '.........',
      '.#...##..',
      '.#.......',
      '......##.',
      '..##.....',
      '.....#...',
      '.##..#...',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 53,
    name: 'Lumen Bridge',
    coinReward: 1356,
    start: (0, 0),
    exit: (6, 9),
    art: const [
      '..........',
      '..##......',
      '..........',
      '...#..##..',
      '...#......',
      '..........',
      '........#.',
      '........#.',
      '...##.....',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 54,
    name: 'Synth Market',
    coinReward: 1378,
    start: (9, 0),
    exit: (0, 8),
    art: const [
      '.........',
      '.##..#...',
      '.....#...',
      '..##.....',
      '.........',
      '.#.......',
      '.#..##...',
      '.........',
      '.........',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 55,
    name: 'Mirror District',
    coinReward: 1400,
    start: (0, 9),
    exit: (6, 0),
    art: const [
      '..........',
      '..........',
      '..........',
      '.......##.',
      '..........',
      '..##......',
      '.......#..',
      '.#...#.#..',
      '.#...#....',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 56,
    name: 'Pulse Avenue',
    coinReward: 1422,
    start: (9, 8),
    exit: (0, 2),
    art: const [
      '.........',
      '..##.....',
      '.........',
      '.....#...',
      '.....#...',
      '.##......',
      '......#..',
      '......#..',
      '.##......',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 57,
    name: 'Aurora Gate',
    coinReward: 1444,
    start: (9, 9),
    exit: (0, 1),
    art: const [
      '..........',
      '...##.....',
      '..........',
      '.....##...',
      '..##......',
      '.......##.',
      '..........',
      '.......#..',
      '..##...#..',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 58,
    name: 'Nova Junction',
    coinReward: 1466,
    start: (9, 8),
    exit: (0, 2),
    art: const [
      '.........',
      '.##....#.',
      '.....#.#.',
      '.....#...',
      '.........',
      '..##.....',
      '.........',
      '..##..#..',
      '......#..',
      '.........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 59,
    name: 'Zenith Field',
    coinReward: 1488,
    start: (0, 0),
    exit: (8, 9),
    art: const [
      '..........',
      '..#.......',
      '..#.......',
      '....##....',
      '.##.......',
      '......##..',
      '..........',
      '.....##...',
      '.##.......',
      '..........',
    ],
  ),
  RouteLevel.grid(
    levelNumber: 60,
    name: 'Crystal Core',
    coinReward: 1510,
    start: (0, 8),
    exit: (9, 0),
    art: const [
      '.........',
      '......#..',
      '.##...#..',
      '.........',
      '....#..#.',
      '....#..#.',
      '..#......',
      '..#......',
      '....##...',
      '.........',
    ],
  ),
];

RouteLevel routeLevelByNumber(int number) => routeLevels.firstWhere(
      (l) => l.levelNumber == number,
      orElse: () => routeLevels.first,
    );
